title: muraho
tagline: A pentest Framework
author: dgatwist
url: https://
permalink: pretty

remote_theme: pmarsceill/just-the-docs
color_scheme: nil
logo: "/images/logo.png"
aux_links:
  "dgatwist on GitHub":
    - "https://github.com/dgatwist/muraho"
footer_content: "Copyright &copy; 2022 dgatwist. Distributed with the <a href=\"https://github.com/dgatwist/muraho/tree/main/LICENSE\">MIT license.</a>"

ga_tracking: UA-111350566-3

plugins:
  - jekyll-seo-tag
